version: "3.3"
services:
  api:
    container_name: ipssi_timer_api_node # Note: Always give unique name to containers to avoid conflict naming
    restart: always
    build: ./
    ports:
      - 8080:8080 # Ports mapping
    volumes:
      - ./:/home/src/app # Volumes mapping - Local -> container
      - /usr/home/app/node_modules
    environment:
      - PORT=8080
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2
    volumes:
      - mongo-storage:/data/db # We add a volume to our container in order to store the database data
    expose:
      - 27017
    ports:
      - 27017:27017

# Volumes definition with connectivity
volumes:
  mongo-storage:
    driver: local
